# Neurodocker version 0.4.0
FROM neurodebian:stretch-non-free

ARG DEBIAN_FRONTEND="noninteractive"

# Libraries needed to compile python
RUN apt-get update \
    && apt-get -y install build-essential libbz2-dev zlib1g-dev libncurses5-dev libgdbm-dev \
    && apt-get -y install libnss3-dev libssl-dev libreadline-dev libffi-dev wget \
    && apt-get -y install -y software-properties-common git curl

# Compiling python 3.7
RUN cd /usr/src \
    && wget https://www.python.org/ftp/python/3.7.9/Python-3.7.9.tgz \
    && tar xzf Python-3.7.9.tgz \
    && cd Python-3.7.9 \
    && ./configure --enable-optimizations \
    && make install

# Install fsl (needed for bet and flirt)
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends fsl-core \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pip3.7 install --upgrade pip \
    && pip3.7 install wheel numpy scipy nilearn matplotlib scikit-image nibabel \
    && pip3.7 install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

RUN mkdir -p ~/.tractseg \
    && mkdir -p /code \
    && curl -SL -o /code/mrtrix3_RC3.tar.gz https://zenodo.org/record/1415322/files/mrtrix3_RC3.tar.gz?download=1

RUN tar -zxf /code/mrtrix3_RC3.tar.gz -C code \
    && /code/mrtrix3/set_path

# Uncomment if we want to rebuild the following commands (otherwise using cache)
RUN echo "rebuild"

RUN pip3.7 install --upgrade https://github.com/MIC-DKFZ/TractSeg/archive/master.zip

# Sometimes fails if running everything from cache -> uncomment line "RUN echo 'rebuild'"
RUN download_all_pretrained_weights

# Does not work -> added mrtrix to path in python
ENV PATH /code/mrtrix3/bin:$PATH

# Using this we can avoid having to call TractSeg each time -> but has problems finding bet then
#ENTRYPOINT ["TractSeg"]

# Does not work
#RUN /bin/bash -c "source /etc/fsl/fsl.sh"
