name: Run tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Run hello world
        run: echo "hello world 3."
        shell: bash
      # - name: Run test script
      #   run: ./.github/scripts/build.sh
      #   shell: bash